
version: "3.9"

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    hostname: localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: netology
      POSTGRES_DB: diploma

  redis:
    image: redis
    ports:
      - "6379:6379"